import { 
    CREATE_USER, 
    FOLLOW_TO_USER, 
    GET_ALL_POST, 
    GET_ALL_SUBSCRIBERS, 
    GET_ALL_SUBSCRIPTIONS, 
    GET_ALL_USERS,
    GET_CURRENT_USER, 
    GET_SINGLE_USER, 
    LOGIN_USER, 
    REFRESH_TOKEN
} from "./api";


export const REQUEST = {
    CREATE_USER,
    LOGIN_USER,
    GET_CURRENT_USER,
    GET_ALL_USERS,
    FOLLOW_TO_USER,
    GET_SINGLE_USER,
    GET_ALL_POST,
    GET_ALL_SUBSCRIBERS,
    GET_ALL_SUBSCRIPTIONS,
    REFRESH_TOKEN
};

